fail_fast: false

repos:
-   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
    rev: master
    hooks:
    -   id: clang-format
        args: [--style=file]
    # -   id: cpplint
    # -   id: cppcheck