fail_fast: false
repos:
  - repo: https://gitee.com/huzhenhong/pre-commit-hooks-cpp
    rev: master
    hooks:
      - id: clang-format
        args: [--style=file]
      # - id: clang-tidy
      # - id: oclint
      # - id: uncrustify
      # - id: cppcheck
      # - id: cpplint
      # - id: include-what-you-use